[package]
name = "discord_message_downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serenity_self = "0.13.3"
eframe = "0.32.1"
egui-notify = "0.20.0"
egui_extras = "0.32.2"
rfd = "0.15.4"

